//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public int PaidByUserId { get; set; }
        public int ConfirmedByUserId { get; set; }
        public Nullable<int> PaidAmount { get; set; }
    
        public virtual PurchasedTicket PurchasedTicket { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
