//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportSchedule
    {
        public int Id { get; set; }
        public Nullable<int> TransportId { get; set; }
        public Nullable<int> FromStoppageId { get; set; }
        public Nullable<int> ToStoppageId { get; set; }
        public string Day { get; set; }
        public Nullable<int> Time { get; set; }
    
        public virtual Stoppage Stoppage { get; set; }
        public virtual Stoppage Stoppage1 { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
